# Setup
title:               JHU Deep Learning in Genomics Journal Club
tagline:             '<br>When Genomics Sequences Meet Deep Learning'
description:         'This is the website for the Deep Learning in Genomics Journal Club at Johns Hopkins University. We aim to explore and discuss the latest advancements in deep learning applications within genomics.'
logo:                '_images/JHU_wse.png'
url:                 https://jhu-deep-learning-in-genomics.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Kuan-Hao Chao
  url:               https://khchao.com/
  email:             kuanhao.chao@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
